version: '3'
services:
  redis-server:
    image: redis:5.0-alpine
    command: ["redis-server", "--appendonly", "yes"]

  database-server:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: playlist-weather-db

  playlist-server:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis-server
      - database-server