openweather:
  url: http://api.openweathermap.org/data/2.5/
  api-key: b77e07f479efe92156376a8b07640ced

spotify:
  clientId: c7aaac525aed462baacbcfc1f64e185a
  secretKey: 85bdbf29451e43d1976953eaa4a76afd


spring:
  profiles:
    active: release
  cache:
    type: redis
    redis:
      time-to-live: 86400
  redis:
    host: redis-server
    port: 6379

  datasource:
    url: jdbc:postgresql://database-server:5432/playlist-weather-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
  flyway:
    enabled: true

---
spring:
  profiles: test
  cache:
    type: NONE

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_test
    driverClassName: org.postgresql.Driver
    username: postgres-user-test
    password: postgres-passwd-test
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      maximum-pool-size: 10